-- CREATE DATABASE OFFICE;
-- use OFFICE;
-- CREATE TABLE SECTORS(
-- SECTOR_ID INT,
-- SECTOR_NAME VARCHAR(50),
-- SECTOR_DEPT VARCHAR(50),
-- SECTOR_POSITION VARCHAR(50),
-- SECTOR_SALARY INT
-- );

-- INSERT INTO SECTORS (SECTOR_ID, SECTOR_NAME, SECTOR_DEPT, SECTOR_POSITION, SECTOR_SALARY) VALUES
-- (101, "ARUN", "IT","SOFTWARE ENGINEER", 100000),
-- (110, "BALA", "AUTOMOBILE","ENGINEER", 50000),
-- (141, "RAJ", "IT","DEVELOPER", 75000),
-- (121, "MANI", "ECE","SOFTWARE ENGINEER", 25000),
-- (111, "VARUN", "MECHANICAL","SOFTWARE ENGINEER", 30000),
-- (181, "VEL", "CIVIL","SOFTWARE ENGINEER", 27000),
-- (131, "SABARI", "MECHANICAL","SOFTWARE ENGINEER", 35000),
-- (123, "VIKRAM", "ELECTRICAL","SOFTWARE ENGINEER", 47000),
-- (174, "LAVANYA", "CIVIL","SOFTWARE ENGINEER", 60000),
-- (157, "VIJI", "AUTOMOBILE","SOFTWARE ENGINEER", 40000),
-- (183, "SRINI", "IT","ENGINEER", 70000),
-- (125, "AJAY", "IT","AUTOMATION TESTER", 25000),
-- (002, "ANAND", "IT","DESIGNER", 45000),
-- (005, "LIJO", "IT","DEVELOPER", 50000),
-- (83, "KARTHIK", "IT","REACT DEVELOPER", 25000),
-- (91, "MOHAN", "IT","DEVELOPER", 95000),
-- (101, "VISHAL", "IT","UI DESIGNER", 55000)


-- MORE THAN 10 NAMES
-- SELECT SECTOR_DEPT, COUNT(*) AS total_employees
-- FROM SECTORS
-- GROUP BY SECTOR_DEPT
-- HAVING COUNT(*) > 10;


-- WHERE BY AVG SALARY
-- SELECT SECTOR_DEPT, AVG(SECTOR_SALARY) AS avg_salary
-- FROM SECTORS
-- GROUP BY SECTOR_DEPT
-- HAVING AVG(SECTOR_SALARY) > 60000;


-- WHERE BY MAX SALARY
-- SELECT SECTOR_POSITION, MAX(SECTOR_SALARY) AS MAX_SALARY
-- FROM SECTORS
-- GROUP BY SECTOR_POSITION
-- HAVING MAX(SECTOR_SALARY) > 80000;


-- GROUP BY TOTAL SALARY
-- SELECT SECTOR_DEPT, SUM(SECTOR_SALARY) AS total_salary
-- FROM SECTORS
-- GROUP BY SECTOR_DEPT
-- HAVING SUM(SECTOR_SALARY) > 50000;


-- ALL COLUMN 
-- SELECT * FROM SECTORS


-- SPECIFIC COLUMN
-- SELECT SECTOR_ID, SECTOR_NAME, SECTOR_SALARY FROM SECTORS;


-- WITH COLUMN WISE
-- SELECT SECTOR_ID AS ID,
-- SECTOR_NAME AS EMP_NAME,
-- SECTOR_SALARY AS SALARY,
-- SECTOR_POSITION AS POSITION,
-- SECTOR_DEPT AS DEPARTMENT
-- FROM SECTORS;



-- WHERE SALARY_WISE
-- SELECT * FROM SECTORS WHERE SECTOR_SALARY > 55000;


-- WHERE DEPT WISE
-- SELECT * FROM SECTORS WHERE SECTOR_DEPT = 'IT';


-- MULTIPLE CONDITION AND
-- SELECT * FROM SECTORS WHERE SECTOR_DEPT = 'IT' AND SECTOR_SALARY > 60000;


-- WITH LIKE PATTERN
-- SELECT * FROM SECTORS WHERE SECTOR_NAME LIKE 'A%';
-- SELECT * FROM SECTORS WHERE SECTOR_NAME LIKE 'V%';


-- SORT BY DESC ASC
-- SELECT * FROM SECTORS ORDER BY SECTOR_SALARY DESC;
-- SELECT * FROM SECTORS ORDER BY SECTOR_SALARY ASC;


-- ASC & DESC
-- SELECT * FROM SECTORS ORDER BY SECTOR_DEPT ASC, SECTOR_SALARY DESC;



-- FIRST 10, 5 RECORDS
-- SELECT * FROM SECTORS LIMIT 10;
-- SELECT * FROM SECTORS LIMIT 5;


-- NEXT 10 RECORD DISPLAY
-- SELECT * FROM SECTORS LIMIT 10 OFFSET 10;


-- UNIQUE DEPT
-- SELECT DISTINCT SECTOR_DEPT FROM SECTORS;
-- SELECT DISTINCT SECTOR_SALARY FROM SECTORS;


-- COUNT DISTINCT DEPT
-- SELECT COUNT(DISTINCT SECTOR_DEPT) AS TOTAL_DEPARTMENTS FROM SECTORS;
-- SELECT COUNT(DISTINCT SECTOR_POSITION) AS TOTAL_POSITION FROM SECTORS;


-- COUNT WISE DEPT
-- SELECT SECTOR_DEPT, COUNT(*) AS SECTOR_COUNT
-- FROM SECTORS
-- GROUP BY SECTOR_DEPT


-- AVG SALARY
-- SELECT SECTOR_DEPT, AVG(SECTOR_SALARY) AS AVG_SALARY
-- FROM SECTORS
-- GROUP BY SECTOR_DEPT;



-- TOTAL SALARY
-- SELECT SECTOR_DEPT, SUM(SECTOR_SALARY) AS TOTAL_SALARY
-- FROM SECTORS
-- GROUP BY SECTOR_DEPT;




-- MAX SALARY AND MIN SALARY
-- SELECT SECTOR_DEPT, MAX(SECTOR_SALARY) AS MAX_SALARY
-- FROM SECTORS
-- GROUP BY SECTOR_DEPT;

-- SELECT SECTOR_DEPT, MIN(SECTOR_SALARY) AS MIN_SALARY
-- FROM SECTORS
-- GROUP BY SECTOR_DEPT;




-- DEPT + POSITION
-- SELECT SECTOR_DEPT, SECTOR_POSITION, COUNT(*) AS COUNT_SECTOR
-- FROM SECTORS
-- GROUP BY SECTOR_DEPT, SECTOR_POSITION;


-- DEPT WITH 5 NAMES
-- SELECT SECTOR_DEPT, COUNT(*) AS SECTOR_COUNT
-- FROM SECTORS
-- GROUP BY SECTOR_DEPT
-- HAVING COUNT(*) > 5;


-- AVG SALARY
-- SELECT SECTOR_DEPT, AVG(SECTOR_SALARY) AS AVG_SALARY
-- FROM SECTORS
-- GROUP BY SECTOR_DEPT
-- HAVING AVG(SECTOR_SALARY) > 50000;

-- TOTAL SALARY
-- SELECT SECTOR_DEPT, SUM(SECTOR_SALARY) AS TOTAL_SALARY
-- FROM SECTORS
-- GROUP BY SECTOR_DEPT
-- HAVING SUM(SECTOR_SALARY) > 500000;


-- MULTIPLE HAVING CONDITIONS
-- SELECT SECTOR_DEPT, COUNT(*) AS SECTOR_COUNT, AVG(SECTOR_SALARY) AS AVG_SALARY
-- FROM SECTORS
-- GROUP BY SECTOR_DEPT
-- HAVING COUNT(*) > 5 AND AVG(SECTOR_SALARY) > 60000;


-- MAX SALARY
-- SELECT SECTOR_DEPT, MAX(SECTOR_SALARY) AS MAX_SALARY
-- FROM SECTORS
-- GROUP BY SECTOR_DEPT
-- HAVING MAX(SECTOR_SALARY) > 75000;



-- SELECT WITH ALL CLAUSE --
-- SELECT SECTOR_DEPT, COUNT(*) AS SECTOR_COUNT, AVG(SECTOR_SALARY) AS AVG_SALARY
-- FROM SECTORS
-- WHERE SECTOR_SALARY > 40000
-- GROUP BY SECTOR_DEPT
-- HAVING AVG(SECTOR_SALARY) > 50000
-- ORDER BY AVG_SALARY DESC
-- LIMIT 5;

-- GROUP BY WITH ORDER BY --
-- SELECT SECTOR_DEPT, SUM(SECTOR_SALARY) AS TOTAL_SALARY
-- FROM SECTORS 
-- GROUP BY SECTOR_DEPT
-- ORDER BY TOTAL_SALARY DESC;


-- WHERE GROUP BY HAVING --
-- SELECT SECTOR_DEPT, COUNT(*) AS SECTOR_COUNT, AVG(SECTOR_SALARY) AS AVG_SALARY
-- FROM SECTORS
-- WHERE SECTOR_SALARY > 30000
-- GROUP BY SECTOR_DEPT
-- HAVING COUNT(*) > 3;




-- DISTINCT WITH WHERE
-- SELECT DISTINCT SECTOR_DEPT
-- FROM SECTORS
-- WHERE SECTOR_SALARY > 60000;

-- SELECT DISTINCT SECTOR_SALARY
-- FROM SECTORS
-- WHERE SECTOR_DEPT = 'IT';



-- MULTIPLE AGGREGATE PER GROUP
-- SELECT SECTOR_DEPT, 
-- COUNT(*) AS SECTOR_COUNT,
-- AVG(SECTOR_SALARY) AS AVG_SALARY,
-- MIN(SECTOR_SALARY) AS MIN_SALARY,
-- MAX(SECTOR_SALARY) AS MAX_SALARY,
-- SUM(SECTOR_SALARY) AS TOTAL_SALARY
-- FROM SECTORS
-- GROUP BY SECTOR_DEPT;


-- NESTED CONDITIONS
-- SELECT * FROM SECTORS
-- WHERE (SECTOR_DEPT = 'IT' AND SECTOR_SALARY > 60000)
-- OR (SECTOR_DEPT = 'CIVIL' AND SECTOR_SALARY > 50000);


-- REPORTED STYLE QUERY
-- SELECT SECTOR_DEPT,
-- COUNT(*) AS SECTOR_COUNT,
-- AVG(SECTOR_SALARY) AS AVG_SALARY,
-- MIN(SECTOR_SALARY) AS MIN_SALARY,
-- MAX(SECTOR_SALARY) AS MAX_SALARY,
-- SUM(SECTOR_SALARY) AS TOTAL_SALARY
-- FROM SECTORS
-- WHERE SECTOR_SALARY > 30000
-- GROUP BY SECTOR_DEPT
-- HAVING AVG(SECTOR_SALARY) > 45000
-- ORDER BY TOTAL_SALARY DESC
-- LIMIT 10;


SELECT * FROM SECTORS